/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.76
 * Generated at: 2017-03-31 09:16:40 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
 
	if(session.getAttribute("student") != null)
		response.sendRedirect("studentIndex");

      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"utf-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("\r\n");
      out.write("    <title>My Club</title>\r\n");
      out.write("    <link rel=\"shortcut icon\" href=\"favicon.ico\"> \r\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/libs/oj/v3.0.0/alta/oj-alta-min.css\" type=\"text/css\"/>\r\n");
      out.write("    \r\n");
      out.write("    <script data-main=\"js/login\" src=\"js/libs/require/require.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("<header class=\"dfml-appheader\" style=\"padding:10px;\">\r\n");
      out.write("            <div class=\"oj-flex oj-flex-items-pad dfml-appheader-classic\">\r\n");
      out.write("                <div class=\"oj-flex-item\">\r\n");
      out.write("                    <div class=\"dfml-appheader-logo\" >\r\n");
      out.write("                        <div class=\"dfml-appheader-logo-block\">\r\n");
      out.write("                            <span role=\"img\" class=\"oj-icon dfml-appheader-logo-oracle\" data-bind=\"attr:{title:labels.logoTitle}\"></span>  \r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"dfml-appheader-appname-block\">\r\n");
      out.write("                            <span class=\"dfml-appheader-appname\" data-bind=\"text: labels.appName\"></span>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </header>\r\n");
      out.write("   <div class=\"oj-flex\">\r\n");
      out.write("            <div id=\"dfml-main-content-area\" class=\"oj-flex-item\"> \r\n");
      out.write("                <div role=\"main\" class=\"demo-page-content-area\">\r\n");
      out.write("                    <div class=\"oj-flex oj-flex-items-pad oj-sm-justify-content-center\" style=\"padding-top:15%;\" >  \r\n");
      out.write("                        <div class=\"oj-flex-item oj-sm-8 oj-md-4 oj-lg-3\">    \r\n");
      out.write("                        <div id=\"form-container1\" class=\"oj-form-layout\">\r\n");
      out.write("                            <form class=\"oj-form\" data-bind=\"submit:doLogin\">\r\n");
      out.write("                                <div class=\"oj-flex\">  \r\n");
      out.write("                                    <div class=\"oj-flex-item\">\r\n");
      out.write("                                        <label for=\"username\" data-bind=\"text:labels.userName\"><span data-bi></span></label>\r\n");
      out.write("                                        <input id=\"username\" type=\"text\" \r\n");
      out.write("                                            data-bind=\"value: username, ojComponent: {component: 'ojInputText', value: username, required:true, invalidComponentTracker: tracker, rootAttributes: { style: 'max-width:25em'}}\"/>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"oj-flex\">  \r\n");
      out.write("                                    <div class=\"oj-flex-item\">\r\n");
      out.write("                                        <label for=\"password\" data-bind=\"text:labels.password\"></label>\r\n");
      out.write("                                        <input id=\"password\" type=\"text\" \r\n");
      out.write("                                           data-bind=\"value: password, ojComponent: {component: 'ojInputPassword', value: password,  required:true, invalidComponentTracker: tracker,  rootAttributes: { style: 'max-width:25em'}}\"/>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"oj-flex\">  \r\n");
      out.write("                                    <div class=\"oj-flex-item\">\r\n");
      out.write("                                            <button id=\"loginButton\" type=\"submit\" \r\n");
      out.write("                                                    data-bind=\"ojComponent: { component: 'ojButton', label: labels.actionLable,  rootAttributes: { style: 'max-width:25em'}}\">\r\n");
      out.write("                                                 </button>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"oj-flex\">  \r\n");
      out.write("                                    <div class=\"oj-flex-item loginerror\" data-bind=\"text:errorMessage\">\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </form>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        </div>    \r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
