/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.76
 * Generated at: 2017-03-28 09:27:25 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;
import com.clemson.model.*;

public final class adminIndex_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write(' ');
      out.write('\r');
      out.write('\n');
 
	if(session.getAttribute("admin") == null)
		response.sendRedirect(request.getContextPath() + "/adminLogin");

      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("    <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\" />\r\n");
      out.write("    <title>华东师范大学自主招生系统 - 管理系统</title>\r\n");
      out.write("\r\n");
      out.write("    <!--[if lt IE 9]>\r\n");
      out.write("    <meta http-equiv=\"refresh\" content=\"0;ie.html\" />\r\n");
      out.write("    <![endif]-->\r\n");
      out.write("    <link href=\"css/bootstrap.min14ed.css?v=3.3.6\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"css/font-awesome.min93e3.css?v=4.4.0\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"css/animate.min.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"css/style.min862f.css?v=4.1.0\" rel=\"stylesheet\">\r\n");
      out.write("<script>!function(e){var c={nonSecure:\"8123\",secure:\"8124\"},t={nonSecure:\"http://\",secure:\"https://\"},r={nonSecure:\"127.0.0.1\",secure:\"gapdebug.local.genuitec.com\"},n=\"https:\"===window.location.protocol?\"secure\":\"nonSecure\";script=e.createElement(\"script\"),script.type=\"text/javascript\",script.async=!0,script.src=t[n]+r[n]+\":\"+c[n]+\"/codelive-assets/bundle.js\",e.getElementsByTagName(\"head\")[0].appendChild(script)}(document);</script></head>\r\n");
      out.write("\r\n");
      out.write("<body class=\"fixed-sidebar full-height-layout gray-bg\" style=\"overflow:hidden\">\r\n");
      out.write("    <div id=\"wrapper\" data-genuitec-lp-enabled=\"false\" data-genuitec-file-id=\"wc1-1\" data-genuitec-path=\"/Clemson/src/main/webapp/WEB-INF/jsp/adminIndex.jsp\"> \r\n");
      out.write("        <nav class=\"navbar-default navbar-static-side\" role=\"navigation\">\r\n");
      out.write("            <div class=\"nav-close\"><i class=\"fa fa-times-circle\"></i>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div>\r\n");
      out.write("                <ul class=\"nav\" id=\"side-menu\">\r\n");
      out.write("                    <li class=\"nav-header\">\r\n");
      out.write("                        <div class=\"dropdown profile-element\">\r\n");
      out.write("                            \r\n");
      out.write("                            <a data-toggle=\"dropdown\" class=\"dropdown-toggle\" href=\"#\">\r\n");
      out.write("                                <span class=\"clear\">\r\n");
      out.write("                                <span class=\"block m-t-xs\"><strong class=\"font-bold\">");
 if(session.getAttribute("admin")!=null) out.println(((Admin) session.getAttribute("admin")).getAdminName()); 
      out.write("</strong></span>\r\n");
      out.write("                                <span class=\"text-muted text-xs block\">管理员<b class=\"caret\"></b></span>\r\n");
      out.write("                                </span>\r\n");
      out.write("                            </a>\r\n");
      out.write("                            <ul class=\"dropdown-menu animated fadeInRight m-t-xs\">\r\n");
      out.write("                                <li>\r\n");
      out.write("                                    <a href=\"");
      out.print(request.getContextPath());
      out.write("/adminLogout\">退出</a>\r\n");
      out.write("                                </li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <a>\r\n");
      out.write("                            <i class=\"glyphicon glyphicon-pencil\"></i>\r\n");
      out.write("                            <span class=\"nav-label\">考试类型管理</span>\r\n");
      out.write("                            <span class=\"fa arrow\"></span>\r\n");
      out.write("                        </a>\r\n");
      out.write("                        <ul class=\"nav nav-second-level\">\r\n");
      out.write("                            <li>\r\n");
      out.write("                                <a class=\"J_menuItem\" href=\"adminTestType\">考试大类设置</a>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li>\r\n");
      out.write("                                <a class=\"J_menuItem\" href=\"adminTestSubType\">考试小类设置</a>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li>\r\n");
      out.write("                                <a class=\"J_menuItem\" href=\"adminTestSubject\">考试科目设置</a>\r\n");
      out.write("                            </li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <a class=\"J_menuItem\" href=\"adminTestManagement\"><i class=\"glyphicon glyphicon-file\"></i> <span class=\"nav-label\">考试管理</span></a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <a>\r\n");
      out.write("                            <i class=\"glyphicon glyphicon-book\"></i>\r\n");
      out.write("                            <span class=\"nav-label\">复试管理</span>\r\n");
      out.write("                            <span class=\"fa arrow\"></span>\r\n");
      out.write("                        </a>\r\n");
      out.write("                        <ul class=\"nav nav-second-level\">\r\n");
      out.write("                            <li>\r\n");
      out.write("                                <a class=\"J_menuItem\" href=\"adminTestQuestion\">复试试题管理</a>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li>\r\n");
      out.write("                                <a class=\"J_menuItem\" href=\"adminTestSchoolRetest\">复试考场管理&<br/>复试录取分数设置</a>\r\n");
      out.write("                            </li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <a>\r\n");
      out.write("                            <i class=\"glyphicon glyphicon-map-marker\"></i>\r\n");
      out.write("                            <span class=\"nav-label\">考试地点管理</span>\r\n");
      out.write("                            <span class=\"fa arrow\"></span>\r\n");
      out.write("                        </a>\r\n");
      out.write("                        <ul class=\"nav nav-second-level\">\r\n");
      out.write("                            <li>\r\n");
      out.write("                                <a class=\"J_menuItem\" href=\"adminSchool\">考点设置</a>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li>\r\n");
      out.write("                                <a class=\"J_menuItem\" href=\"adminClass\">考场设置</a>\r\n");
      out.write("                            </li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    \r\n");
      out.write("                    <li>\r\n");
      out.write("                        <a class=\"J_menuItem\" href=\"adminTestArrange\"><i class=\"fa fa-columns\"></i> <span class=\"nav-label\">科目考场分配</span></a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    \r\n");
      out.write("                    <li>\r\n");
      out.write("                        <a class=\"J_menuItem\" href=\"adminTestStudent\"><i class=\"glyphicon glyphicon-user\"></i> <span class=\"nav-label\">考生信息管理</span></a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <a>\r\n");
      out.write("                            <i class=\"glyphicon glyphicon-folder-open\"></i>\r\n");
      out.write("                            <span class=\"nav-label\">考生成绩管理管理</span>\r\n");
      out.write("                            <span class=\"fa arrow\"></span>\r\n");
      out.write("                        </a>\r\n");
      out.write("                        <ul class=\"nav nav-second-level\">\r\n");
      out.write("                            <li>\r\n");
      out.write("                                <a class=\"J_menuItem\" href=\"adminTestMark\">正式成绩管理</a>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li>\r\n");
      out.write("                                <a class=\"J_menuItem\" href=\"adminTestMarkRe\">复试成绩管理</a>\r\n");
      out.write("                            </li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <a class=\"J_menuItem\" href=\"adminSetsumei\"><i class=\"glyphicon glyphicon-list-alt\"></i> <span class=\"nav-label\">说明文字管理</span></a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                     \r\n");
      out.write("                </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("        </nav>\r\n");
      out.write("       \r\n");
      out.write("        <div id=\"page-wrapper\" class=\"gray-bg dashbard-1\">\r\n");
      out.write("\r\n");
      out.write("            <div class=\"row J_mainContent\" id=\"content-main\">\r\n");
      out.write("                <iframe class=\"J_iframe\" name=\"iframe0\" width=\"100%\" height=\"100%\" src=\"adminTestType\" frameborder=\"0\" seamless></iframe>\r\n");
      out.write("            </div>\r\n");
      out.write("             \r\n");
      out.write("        </div>\r\n");
      out.write(" \r\n");
      out.write("    </div>\r\n");
      out.write("    <script src=\"js/jquery.min.js?v=2.1.4\"></script>\r\n");
      out.write("    <script src=\"js/bootstrap.min.js?v=3.3.6\"></script>\r\n");
      out.write("    <script src=\"js/plugins/metisMenu/jquery.metisMenu.js\"></script>\r\n");
      out.write("    <script src=\"js/plugins/slimscroll/jquery.slimscroll.min.js\"></script>\r\n");
      out.write("    <script src=\"js/plugins/layer/layer.min.js\"></script>\r\n");
      out.write("    <script src=\"js/hplus.min.js?v=4.1.0\"></script>\r\n");
      out.write("    <script type=\"text/javascript\" src=\"js/contabs.min.js\"></script>\r\n");
      out.write("    <script src=\"js/plugins/pace/pace.min.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
