/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.76
 * Generated at: 2017-03-27 05:37:45 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;
import java.util.*;
import com.clemson.model.*;
import java.util.*;

public final class enroll_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/WEB-INF/jsp/sidebar.jsp", Long.valueOf(1490588881784L));
    _jspx_dependants.put("/WEB-INF/jsp/session.jsp", Long.valueOf(1490588881771L));
    _jspx_dependants.put("/WEB-INF/jsp/navbar.jsp", Long.valueOf(1490588881757L));
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
 
	if(session.getAttribute("student") == null)
		response.sendRedirect(request.getContextPath() + "/login");

      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("    <title>华东师范大学自主招生系统</title>\r\n");
      out.write("    \r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\" />\r\n");
      out.write("    \r\n");
      out.write("    <!-- bootstrap -->\r\n");
      out.write("    <link href=\"");
      out.print(request.getContextPath());
      out.write("/css/bootstrap/bootstrap.css\" rel=\"stylesheet\" />\r\n");
      out.write("    <link href=\"");
      out.print(request.getContextPath());
      out.write("/css/bootstrap/bootstrap-responsive.css\" rel=\"stylesheet\" />\r\n");
      out.write("    <link href=\"");
      out.print(request.getContextPath());
      out.write("/css/bootstrap/bootstrap-overrides.css\" type=\"text/css\" rel=\"stylesheet\" />\r\n");
      out.write("    \r\n");
      out.write("    <link href=\"");
      out.print(request.getContextPath());
      out.write("/css/lib/font-awesome.css\" type=\"text/css\" rel=\"stylesheet\" />\r\n");
      out.write("\r\n");
      out.write("    <!-- global styles -->\r\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(request.getContextPath());
      out.write("/css/layout.css\" />\r\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(request.getContextPath());
      out.write("/css/elements.css\" />\r\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(request.getContextPath());
      out.write("/css/icons.css\" />\r\n");
      out.write("\r\n");
      out.write("    <!-- this page specific styles -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath());
      out.write("/css/compiled/index.css\" type=\"text/css\" media=\"screen\" />     \r\n");
      out.write("    <!--[if lt IE 9]>\r\n");
      out.write("      <script src=\"http://html5shim.googlecode.com/svn/trunk/html5.js\"></script>\r\n");
      out.write("    <![endif]-->\r\n");
      out.write("    \r\n");
      out.write("    <meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\" />\r\n");
      out.write("    <script type=\"text/javascript\" src=\"");
      out.print(request.getContextPath());
      out.write("/js/jquery.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath());
      out.write("/css/compiled/user-list.css\" type=\"text/css\" media=\"screen\" /> \r\n");
      out.write("    <!-- libraries -->\r\n");
      out.write("    <link href=\"");
      out.print(request.getContextPath());
      out.write("/css/lib/jquery-ui-1.10.2.custom.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("\r\n");
      out.write("    <!-- sweetalert -->\r\n");
      out.write("    <link href=\"");
      out.print(request.getContextPath());
      out.write("/css/plugins/sweetalert/sweetalert.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("    <!-- global styles -->\r\n");
      out.write("    <link rel=\"shortcut icon\" href=\"favicon.ico\">\r\n");
      out.write("    <link href=\"");
      out.print(request.getContextPath());
      out.write("/css/font-awesome.min93e3.css?v=4.4.0\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("    <link href=\"");
      out.print(request.getContextPath());
      out.write("/css/animate.min.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"");
      out.print(request.getContextPath());
      out.write("/css/style.min862f.css?v=4.1.0\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("<script>\"undefined\"==typeof CODE_LIVE&&(!function(e){var t={nonSecure:\"51552\",secure:\"51557\"},c={nonSecure:\"http://\",secure:\"https://\"},r={nonSecure:\"127.0.0.1\",secure:\"gapdebug.local.genuitec.com\"},n=\"https:\"===window.location.protocol?\"secure\":\"nonSecure\";script=e.createElement(\"script\"),script.type=\"text/javascript\",script.async=!0,script.src=c[n]+r[n]+\":\"+t[n]+\"/codelive-assets/bundle.js\",e.getElementsByTagName(\"head\")[0].appendChild(script)}(document),CODE_LIVE=!0);</script></head>\r\n");
      out.write("<body  style=\"background-size:cover;overflow:-Scroll;\" data-genuitec-lp-enabled=\"false\" data-genuitec-file-id=\"wc1-56\" data-genuitec-path=\"/Clemson/src/main/webapp/WEB-INF/jsp/enroll.jsp\"> \r\n");
      out.write("    <!-- navbar -->\r\n");
      out.write("    ");
      out.write(" \r\n");
      out.write("    <div class=\"navbar navbar-inverse\" data-genuitec-lp-enabled=\"false\" data-genuitec-file-id=\"wc1-73\" data-genuitec-path=\"/Clemson/src/main/webapp/WEB-INF/jsp/navbar.jsp\">\r\n");
      out.write("        <div class=\"navbar-inner\">\r\n");
      out.write("            <a class=\"brand\" href=\"");
      out.print(request.getContextPath());
      out.write("/studentIndex\">华东师范大学自主招生系统</a>\r\n");
      out.write("            <ul class=\"nav pull-right\">   \r\n");
      out.write("                <li class=\"dropdown\">\r\n");
      out.write("                    <a href=\"#\" class=\"dropdown-toggle hidden-phone\" data-toggle=\"dropdown\" style=\"font-family: 'Open Sans', sans-serif; font-size:12px; font-weight:600;\">你好，");
 if(session.getAttribute("student")!=null) out.println(((Student) session.getAttribute("student")).getStudentName()); 
      out.write("<b class=\"caret\"></b></a>\r\n");
      out.write("                    <ul class=\"dropdown-menu\">\r\n");
      out.write("                        <li><a href=\"");
      out.print(request.getContextPath());
      out.write("/logout\">注销</a></li>\r\n");
      out.write("                        <li><a href=\"#\">修改密码</a></li> \r\n");
      out.write("                    </ul>\r\n");
      out.write("                </li> \r\n");
      out.write("            </ul>            \r\n");
      out.write("        </div>\r\n");
      out.write("    </div>");
      out.write(" \r\n");
      out.write("    <!-- end navbar -->\r\n");
      out.write("\r\n");
      out.write("    <!-- sidebar -->\r\n");
      out.write("    ");
      out.write(" \r\n");
      out.write("<div id=\"sidebar-nav\" data-genuitec-lp-enabled=\"false\" data-genuitec-file-id=\"wc1-75\" data-genuitec-path=\"/Clemson/src/main/webapp/WEB-INF/jsp/sidebar.jsp\">\r\n");
      out.write("        <img class=\"ecnu\" src=\"");
      out.print(request.getContextPath());
      out.write("/img/saber.jpg\" alt=\"\"/>\r\n");
      out.write("        <ul id=\"dashboard-menu\">  \r\n");
      out.write("            <li> \r\n");
      out.write("                <a href=\"");
      out.print(request.getContextPath());
      out.write("/studentIndex\">  \r\n");
      out.write("                    <i class=\"icon-home\"></i>\r\n");
      out.write("                    <span style=\"font-size:12px\">报名信息首页</span>\r\n");
      out.write("                </a>\r\n");
      out.write("            </li>        \r\n");
      out.write("             <li>\r\n");
      out.write("                <a href=\"");
      out.print(request.getContextPath());
      out.write("/type\"> \r\n");
      out.write("                    <i class=\"icon-star-half\"></i>\r\n");
      out.write("                    <span style=\"font-size:12px\">考试报名</span>\r\n");
      out.write("                </a>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li>\r\n");
      out.write("                <a href=\"#\"> \r\n");
      out.write("                    <i class=\"icon-edit\"></i>\r\n");
      out.write("                    <span style=\"font-size:12px\">修改密码</span>\r\n");
      out.write("                </a>\r\n");
      out.write("            </li>\r\n");
      out.write("            \r\n");
      out.write("        </ul>\r\n");
      out.write("</div>\r\n");
      out.write(" \r\n");
      out.write("    <!-- end sidebar -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <!-- main container -->\r\n");
      out.write("        <!-- main container -->\r\n");
      out.write("    <div class=\"content\" data-genuitec-lp-enabled=\"false\" data-genuitec-file-id=\"wc1-56\" data-genuitec-path=\"/Clemson/src/main/webapp/WEB-INF/jsp/enroll.jsp\">      \r\n");
      out.write("        <div class=\"container-fluid\">\r\n");
      out.write("            <div id=\"pad-wrapper\" class=\"form-page\">\r\n");
      out.write("                <div class=\"row-fluid form-wrapper\">\r\n");
      out.write("                    <!-- left column -->\r\n");
      out.write("                    <div class=\"span8 column b-r\">\r\n");
      out.write("                        <form method=\"post\" action=\"");
      out.print(request.getContextPath());
      out.write('/');
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${postURL}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\" accept-charset=\"utf-8\" name=\"form1\">\r\n");
      out.write("                            <div class=\"ibox float-e-margins\">\r\n");
      out.write("                                <div class=\"ibox-title\">\r\n");
      out.write("                                    <h2>您的基本信息</h2>\r\n");
      out.write("                                    <div class=\"ibox-tools\">\r\n");
      out.write("                                        <a class=\"btn-flat default collapse-link\">收起</a>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"ibox-content\">\r\n");
      out.write("                                    <table class=\"table table-striped\">\r\n");
      out.write("                                        <tr>\r\n");
      out.write("                                            <td>身份证号：</td>\r\n");
      out.write("                                            <td>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${student.idcNumber}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("</td>\r\n");
      out.write("                                            <td>姓名：</td>\r\n");
      out.write("                                            <td>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${student.studentName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("</td>\r\n");
      out.write("                                        </tr>\r\n");
      out.write("                                        <tr>\r\n");
      out.write("                                            <td>性别：</td>\r\n");
      out.write("                                            <td>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${student.studentSex}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("</td>\r\n");
      out.write("                                            <td>民族：</td>\r\n");
      out.write("                                            <td>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${student.studentNation}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("</td>\r\n");
      out.write("                                        </tr>\r\n");
      out.write("                                        <tr>\r\n");
      out.write("                                            <td>出生日期：</td>\r\n");
      out.write("                                            <td>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${student.studentBirthday}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("</td>\r\n");
      out.write("                                            <td>家庭住址：</td>\r\n");
      out.write("                                            <td>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${student.studentAddress}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("</td>\r\n");
      out.write("                                        </tr>\r\n");
      out.write("                                        <tr>\r\n");
      out.write("                                            <td>就读高中：</td>\r\n");
      out.write("                                            <td>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${student.studentSchool}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("</td>\r\n");
      out.write("                                            <td>电子邮箱：</td>\r\n");
      out.write("                                            <td>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${student.studentEmail}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("</td>\r\n");
      out.write("                                        </tr>\r\n");
      out.write("                                        <tr>\r\n");
      out.write("                                            <td>高考报名号：</td>\r\n");
      out.write("                                            <td>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${student.ceeNumber}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("</td>\r\n");
      out.write("                                            <td>艺术号：</td>\r\n");
      out.write("                                            <td>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${student.artNumber}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("</td>\r\n");
      out.write("                                        </tr>\r\n");
      out.write("                                    </table>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                \r\n");
      out.write("                                <div class=\"ibox-title\">\r\n");
      out.write("                                    <h2>您的报考信息</h2>\r\n");
      out.write("                                    <div class=\"ibox-tools\">\r\n");
      out.write("                                        <a class=\"btn-flat default collapse-link\">收起</a>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"ibox-content\">\r\n");
      out.write("                                    <table class=\"table table-striped\">\r\n");
      out.write("                                        <tr>\r\n");
      out.write("                                            <td>考试大类：</td>\r\n");
      out.write("                                            <td>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${test.typeName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("</td>\r\n");
      out.write("                                        </tr>\r\n");
      out.write("                                        <tr>\r\n");
      out.write("                                            <td>考试小类：</td>\r\n");
      out.write("                                            <td>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${test.subTypeName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("</td>\r\n");
      out.write("                                        </tr>\r\n");
      out.write("                                        <tr>\r\n");
      out.write("                                            <td>获得奖项及等级证书：</td>\r\n");
      out.write("                                            <td><textarea name=\"awards\" class=\"span12\" rows=\"4\" placeholder=\"请输入您的相关获奖信息\"></textarea></td>\r\n");
      out.write("                                        </tr>\r\n");
      out.write("                                    </table>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                \r\n");
      out.write("                                <div class=\"fluid\">\r\n");
      out.write("                                <div class=\"span10\"></div>\r\n");
      out.write("                                <div class=\"span2\">\r\n");
      out.write("                                    <a class=\"btn-flat inverse\" href=\"../studentIndex\" style=\"width:34px;text-align:center;\">取消</a>\r\n");
      out.write("                                    <a class=\"btn-flat inverse\" onclick=\"mySubmit();\" style=\"width:34px;text-align:center;\">提交</a>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </form>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    <!-- right column -->\r\n");
      out.write("                    <div class=\"span4 column pull-right\" style=\"text-align:center;font-family:'隶书';\">\r\n");
      out.write("                        <img src=\"");
      out.print(request.getContextPath());
      out.write("/img/login-logo.png\"/>\r\n");
      out.write("                        <br/>\r\n");
      out.write("                        <h1>华东师范大学</h1>\r\n");
      out.write("                        <h3>East China Normal University</h3>\r\n");
      out.write("                        <img src=\"");
      out.print(request.getContextPath());
      out.write("/img/5.jpg\" style=\"margin-top:60px;\"/>\r\n");
      out.write("                        <h3>华东师范大学中山北路校区大门</h3>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(" \r\n");
      out.write("    <script src=\"");
      out.print(request.getContextPath());
      out.write("/js/bootstrap.min.js\"></script>\r\n");
      out.write("    <script src=\"");
      out.print(request.getContextPath());
      out.write("/js/jquery-ui-1.10.2.custom.min.js\"></script>\r\n");
      out.write("    <!-- knob -->\r\n");
      out.write("    <script src=\"");
      out.print(request.getContextPath());
      out.write("/js/jquery.knob.js\"></script> \r\n");
      out.write("    <script src=\"");
      out.print(request.getContextPath());
      out.write("/js/theme.js\"></script>\r\n");
      out.write("\r\n");
      out.write("    <script src=\"");
      out.print(request.getContextPath());
      out.write("/js/content.min.js?v=1.0.0\"></script>\r\n");
      out.write("    <script src=\"");
      out.print(request.getContextPath());
      out.write("/js/plugins/sweetalert/sweetalert.min.js\"></script>\r\n");
      out.write("    <script src=\"");
      out.print(request.getContextPath());
      out.write("/js/jquery-latest.js\"></script>\r\n");
      out.write(" \t\r\n");
      out.write("\t<script>\r\n");
      out.write("    \t$(function(){\r\n");
      out.write("    \t\t$(\"[href='");
      out.print(request.getContextPath());
      out.write("/type']\").parent().addClass(\"active\");\r\n");
      out.write("    \t\t$(\"<div class='pointer'><div class='arrow'></div><div class='arrow_border'></div></div>\").appendTo($(\"[href='");
      out.print(request.getContextPath());
      out.write("/type']\").parent());\r\n");
      out.write("    \t\r\n");
      out.write("    \t});\r\n");
      out.write("    \t\r\n");
      out.write("    \tfunction mySubmit(){\r\n");
      out.write("\t\t\tdocument.form1.submit();\r\n");
      out.write("\t\t}\r\n");
      out.write("    </script> \r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(" \r\n");
      out.write("   ");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
