/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.76
 * Generated at: 2017-03-27 06:52:35 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;
import java.util.*;
import com.clemson.model.*;
import java.util.*;

public final class viewTypeList_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/WEB-INF/jsp/sidebar.jsp", Long.valueOf(1459843346000L));
    _jspx_dependants.put("/WEB-INF/jsp/session.jsp", Long.valueOf(1458765712000L));
    _jspx_dependants.put("/WEB-INF/jsp/navbar.jsp", Long.valueOf(1458768256000L));
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
 
	if(session.getAttribute("student") == null)
		response.sendRedirect(request.getContextPath() + "/login");

      out.write(" \r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("    <title>华东师范大学自主招生系统</title>\r\n");
      out.write("    \r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\" />\r\n");
      out.write("    \r\n");
      out.write("    <!-- bootstrap -->\r\n");
      out.write("    <link href=\"css/bootstrap/bootstrap.css\" rel=\"stylesheet\" />\r\n");
      out.write("    <link href=\"css/bootstrap/bootstrap-responsive.css\" rel=\"stylesheet\" />\r\n");
      out.write("    <link href=\"css/bootstrap/bootstrap-overrides.css\" type=\"text/css\" rel=\"stylesheet\" />\r\n");
      out.write("    \r\n");
      out.write("    <link href=\"css/lib/font-awesome.css\" type=\"text/css\" rel=\"stylesheet\" />\r\n");
      out.write("\r\n");
      out.write("    <!-- global styles -->\r\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"css/layout.css\" />\r\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"css/elements.css\" />\r\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"css/icons.css\" />\r\n");
      out.write("\r\n");
      out.write("    <!-- this page specific styles -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/compiled/index.css\" type=\"text/css\" media=\"screen\" />     \r\n");
      out.write("    <!--[if lt IE 9]>\r\n");
      out.write("      <script src=\"http://html5shim.googlecode.com/svn/trunk/html5.js\"></script>\r\n");
      out.write("    <![endif]-->\r\n");
      out.write("    \r\n");
      out.write("    <meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\" />\r\n");
      out.write("    <script type=\"text/javascript\" src=\"js/jquery.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/compiled/user-list.css\" type=\"text/css\" media=\"screen\" /> \r\n");
      out.write("    <!-- libraries -->\r\n");
      out.write("    <link href=\"css/lib/jquery-ui-1.10.2.custom.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("\r\n");
      out.write("    <!-- global styles -->\r\n");
      out.write("    <link rel=\"shortcut icon\" href=\"favicon.ico\">\r\n");
      out.write("    <link href=\"css/font-awesome.min93e3.css?v=4.4.0\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("    <link href=\"css/animate.min.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"css/style.min862f.css?v=4.1.0\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body style=\"background-size:cover;overflow:-Scroll;overflow-y:hidden\"> \r\n");
      out.write("    <!-- navbar -->\r\n");
      out.write("    ");
      out.write(" \r\n");
      out.write("    <div class=\"navbar navbar-inverse\">\r\n");
      out.write("        <div class=\"navbar-inner\">\r\n");
      out.write("            <a class=\"brand\" href=\"");
      out.print(request.getContextPath());
      out.write("/studentIndex\">华东师范大学自主招生系统</a>\r\n");
      out.write("            <ul class=\"nav pull-right\">   \r\n");
      out.write("                <li class=\"dropdown\">\r\n");
      out.write("                    <a href=\"#\" class=\"dropdown-toggle hidden-phone\" data-toggle=\"dropdown\" style=\"font-family: 'Open Sans', sans-serif; font-size:12px; font-weight:600;\">你好，");
 if(session.getAttribute("student")!=null) out.println(((Student) session.getAttribute("student")).getStudentName()); 
      out.write("<b class=\"caret\"></b></a>\r\n");
      out.write("                    <ul class=\"dropdown-menu\">\r\n");
      out.write("                        <li><a href=\"");
      out.print(request.getContextPath());
      out.write("/logout\">注销</a></li>\r\n");
      out.write("                        <li><a href=\"#\">修改密码</a></li> \r\n");
      out.write("                    </ul>\r\n");
      out.write("                </li> \r\n");
      out.write("            </ul>            \r\n");
      out.write("        </div>\r\n");
      out.write("    </div>");
      out.write(" \r\n");
      out.write("    <!-- end navbar -->\r\n");
      out.write("\r\n");
      out.write("    <!-- sidebar -->\r\n");
      out.write("    ");
      out.write(" \r\n");
      out.write("<div id=\"sidebar-nav\">\r\n");
      out.write("        <img class=\"ecnu\" src=\"");
      out.print(request.getContextPath());
      out.write("/img/saber.jpg\" alt=\"\"/>\r\n");
      out.write("        <ul id=\"dashboard-menu\">  \r\n");
      out.write("            <li> \r\n");
      out.write("                <a href=\"");
      out.print(request.getContextPath());
      out.write("/studentIndex\">  \r\n");
      out.write("                    <i class=\"icon-home\"></i>\r\n");
      out.write("                    <span style=\"font-size:12px\">报名信息首页</span>\r\n");
      out.write("                </a>\r\n");
      out.write("            </li>        \r\n");
      out.write("             <li>\r\n");
      out.write("                <a href=\"");
      out.print(request.getContextPath());
      out.write("/type\"> \r\n");
      out.write("                    <i class=\"icon-star-half\"></i>\r\n");
      out.write("                    <span style=\"font-size:12px\">考试报名</span>\r\n");
      out.write("                </a>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li>\r\n");
      out.write("                <a href=\"#\"> \r\n");
      out.write("                    <i class=\"icon-edit\"></i>\r\n");
      out.write("                    <span style=\"font-size:12px\">修改密码</span>\r\n");
      out.write("                </a>\r\n");
      out.write("            </li>\r\n");
      out.write("            \r\n");
      out.write("        </ul>\r\n");
      out.write("</div>\r\n");
      out.write(" \r\n");
      out.write("    <!-- end sidebar -->\r\n");
      out.write("\r\n");
      out.write("    <!-- main container -->\r\n");
      out.write("        <!-- main container -->\r\n");
      out.write("    <div class=\"content\">\r\n");
      out.write("        <div id=\"pad-wrapper\" class=\"users-list\">\r\n");
      out.write("            <div class=\"wrapper wrapper-content animated fadeInRight\">\r\n");
      out.write("                <div class=\"row\">\r\n");
      out.write("                \r\n");
      out.write("                    <div class=\"ibox float-e-margins\">\r\n");
      out.write("                        <div class=\"ibox-title\"> \r\n");
      out.write("                            <h1>艺术类考生报名入口</h1>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"ibox-content\">\r\n");
      out.write("                            <h2>如果您拥有艺术类特长，曾获得过市级以上艺术类比赛（美术、音乐等）有效奖项（三等奖及以上），<br/><br/>或者拥有相关考试等级证书，可由此报名，参加我校艺术特长生自主招生考试</h2>\r\n");
      out.write("                            <div style=\"margin-top:20px;\">\r\n");
      out.write("                                <a class=\"btn-glow primary\" href=\"type/art/\">点此进入艺术类考生报名界面</a>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        \r\n");
      out.write("                        <div class=\"ibox-title\"> \r\n");
      out.write("                            <h1>体育类考生报名入口</h1>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"ibox-content\">\r\n");
      out.write("                            <h2>如果您拥有体育类特长，曾获得过市级以上运动会或相关竞技比赛有效奖项（三等奖及以上），<br/><br/>或者拥有市级以上运动员等级证书，可由此报名，参加我校体育特长生自主招生考试</h2>\r\n");
      out.write("                            <div style=\"margin-top:20px;\">\r\n");
      out.write("                                <a class=\"btn-glow inverse\" href=\"type/sport/\">点此进入体育类考生报名界面</a>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        \r\n");
      out.write("                        <div class=\"ibox-title\"> \r\n");
      out.write("                            <h1>科技类考生报名入口</h1>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"ibox-content\">\r\n");
      out.write("                            <h2>如果您拥有科技创造特长，曾获得过市级以上科技发明比赛（航模比赛、编程大赛等）有效奖项（三等奖及以上），<br/><br/>或者拥有相关等级证书、专利证书，可由此报名，参加我校科技特长生自主招生考试</h2>\r\n");
      out.write("                            <div style=\"margin-top:20px;\">\r\n");
      out.write("                                <a class=\"btn-glow success\" href=\"type/tech/\">点此进入科技类考生报名界面</a>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write(" \r\n");
      out.write("    <script src=\"js/bootstrap.min.js\"></script>\r\n");
      out.write("    <script src=\"js/jquery-ui-1.10.2.custom.min.js\"></script>\r\n");
      out.write("    <!-- knob -->\r\n");
      out.write("    <script src=\"js/jquery.knob.js\"></script> \r\n");
      out.write("    <script src=\"js/theme.js\"></script>\r\n");
      out.write("\r\n");
      out.write("    <script src=\"js/content.min.js?v=1.0.0\"></script>\r\n");
      out.write("    <script>\r\n");
      out.write("    \t$(function(){\r\n");
      out.write("    \t\t$(\"[href='");
      out.print(request.getContextPath());
      out.write("/type']\").parent().addClass(\"active\");\r\n");
      out.write("    \t\t$(\"<div class='pointer'><div class='arrow'></div><div class='arrow_border'></div></div>\").appendTo($(\"[href='");
      out.print(request.getContextPath());
      out.write("/type']\").parent());\r\n");
      out.write("    \t\r\n");
      out.write("    \t});\r\n");
      out.write("    </script>\r\n");
      out.write("    <script src=\"js/jquery-latest.js\"></script>\r\n");
      out.write(" \r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(" \r\n");
      out.write("   ");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
